#!/bin/bash
gmx="singularity exec /scratch/projects/hockygroup/gmh4/projects/gmm_clustering/docker_test/gmx2019.6-plumed-sizeshape_amd64_cuda.sif gmx"
input_dir=../../inputs
data_dir=../../../analyze_data/outputs/clustering
ln -sf ${input_dir}/run_100ns.mdp
ln -sf ${input_dir}/topol.top
ln -sf ${input_dir}/alaA.pdb

ln -sf ${data_dir}/global_avg.txt   
ln -sf ${data_dir}/ld1_coeffs.txt
ln -sf ${data_dir}/global_prec.txt

prefix=alaA_100ns_biasphipsi_h0.5_sigma0.4_BF8
sed -e "s/__PREFIX__/$prefix/" ${input_dir}/plumed_phipsi.dat > plumed_phipsi.dat

$gmx grompp -f run_100ns.mdp -c alaA.pdb -o alaA_100ns.tpr
$gmx mdrun -nt 1 -s alaA_100ns.tpr -plumed plumed_phipsi.dat -deffnm $prefix

mv \#* tmp/
